version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.1.0
  buildpacks: buildpacks/pack@<<pipeline.parameters.dev-orb-version>>

# Pipeline Parameters
parameters:
  ## internal to orb-tools
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  ## internal to orb-tools
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

workflows:
  integration-test:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - buildpacks/build:
          working-directory: samples/apps/ruby-bundler
          image-name: test-image
          builder: heroku/buildpacks:18
          after-checkout:
            - run: git clone --depth=1 https://github.com/buildpacks/samples.git samples
  validate-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: buildpacks/pack
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
  draft-release:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - hold-for-approval:
          filters:
            branches:
              only: /release\/.*/
          type: approval
      - github-release:
          filters:
            branches:
              only: /release\/.*/
          requires:
            - hold-for-approval
  publish:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/publish:
          orb-ref: buildpacks/pack@$CIRCLE_TAG
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

jobs:
  github-release:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Install generator
          command: gem install github_changelog_generator
      - run:
          name: Install releaser
          command: go get -u github.com/tcnksm/ghr
      - checkout
      - run:
          name: Determine version
          command: |
            [[ $CIRCLE_BRANCH =~ ^release/(.*)$ ]] && echo -n ${BASH_REMATCH[1]} > VERSION || (echo "failed to determine version" && exit 99)
            cat VERSION
      - run:
          name: Generate changelog
          command: |
            github_changelog_generator --user $CIRCLE_PROJECT_USERNAME --project $CIRCLE_PROJECT_REPONAME --token $GITHUB_BOT_PAT --future-release $(cat VERSION) -o CHANGELOG.tmp.md
            # remove footer
            head -n -3 CHANGELOG.tmp.md > CHANGELOG.md
            cat CHANGELOG.md
      - run:
          name: Create GH release
          command: |
            VERSION=$(cat VERSION)
            ghr -draft -t $GITHUB_BOT_PAT -c $CIRCLE_SHA1 -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -b "$(cat CHANGELOG.md)" -n "pack-orb ${VERSION}" $VERSION
